name: CNTI1409
encoding: UTF-8
disable_component_resolution_regex_fallback: 1
default_view: VistaPrincipal

# Configuración de la base de datos.
Model::DB:
  schema_class: Validador::Esquema
  connect_info:
    user: admin
    password: 123321...
    dsn: dbi:Pg:dbname=validador;host=localhost
    pg_enable_utf8: 1

# Configuración de las migajitas de pan.
breadcrumbs:
  hide_home: 1
  hide_index: 1
  labels:
    /auditoria: Auditoría
    /auditoria/crear: Crear Auditoría
    /auditoria/detalle: Detalle de la Auditoría
    /auditoria/reporte: Lista de Auditorías
    /entidades: Entidades Verificadoras
    /inicio: Inicio
    /instituciones/listar: Lista de Instituciones
    /instituciones/registrar: Registrar Institución

# Configuración del Módulo de Autenticación LDAP.
authentication:
    default_realm: ldap
    realms:
        ldap:
            credential:
                class: Password
                password_field: password
                password_type:  self_check
            store:
                class: LDAP
                ldap_server: 127.0.0.1
                ldap_server_options:
                    timeout: 30
                binddn: cn=admin,dc=cnti,dc=gob,dc=ve
                bindpw: 123321...
                start_tls: 0
                start_tls_options:
                    verify: none
                user_basedn: ou=Usuarios,ou=cnti1409,dc=cnti,dc=gob,dc=ve
                user_filter: (&(objectClass=posixAccount)(uid=%s))
                user_scope: sub
                user_field: uid
                user_search_options:
                    deref: always
                use_roles: 1
                role_basedn: ou=Roles,ou=cnti1409,dc=cnti,dc=gob,dc=ve
                role_filter: (&(objectClass=posixGroup)(memberUid=%s))
                role_scope: sub
                role_field: cn
                role_value: uid
                role_search_options:
                    deref: always


# Configuración General LDAP. 
# Base de busqueda de Entidades.
base_entidades: ou=Entidades,ou=cnti1409,dc=cnti,dc=gob,dc=ve

# Base de busqueda de Usuarios.
base_usuarios: ou=Usuarios,ou=cnti1409,dc=cnti,dc=gob,dc=ve

# Base de busqueda de los roles.
base_roles: ou=Roles,ou=cnti1409,dc=cnti,dc=gob,dc=ve

# Rama de mantenimiento. 
base_mantenimiento: ou=Mantenimiento,ou=cnti1409,dc=cnti,dc=gob,dc=ve
