---
abstract: 'Catalyst based application'
author:
  - root
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CNTI1409
no_index:
  directory:
    - inc
    - t
requires:
  CSS::Tiny: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::LDAP: 0
  Catalyst::Controller::HTML::FormFu: 0
  Catalyst::Controller::REST: 0
  Catalyst::Model::LDAP: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::Breadcrumbs: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::Runtime: 5.8002
  Config::General: 0
  DBD::Pg: 0
  DateTime::Format::Pg: 0
  HTML::FormFu::Model::DBIC: 0
  LaTeX::Encode: 0
  Moose: 0
  Sub::Uplevel: 0
  Template::Latex: 0
  WWW::Mechanize::Cached: 0
  XML::LibXML: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
