package AracnoiDB::Model::CNTI::SpiderDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'CNTI::SpiderDB',
    
    connect_info => {
        dsn => 'dbi:SQLite:dbname=spiderdb',
        user => '',
        password => '',
    }
);

=head1 NAME

AracnoiDB::Model::CNTI::SpiderDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<AracnoiDB>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<CNTI::SpiderDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

jrey

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
