package CNTI1409::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Validador::Esquema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=validador;host=localhost',
        user => 'admin',
        password => '123321...',
		pg_enable_utf8 => 1,
    }
);

=head1 NAME

CNTI1409::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<CNTI1409>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Validador::Esquema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.4

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
